# Versionsdatei des Update-Servers
version.url=https://www.pcnd.eu/jpcnd/version/jpcnd-prog-version.txt
db.version.url=https://www.pcnd.eu/jpcnd/version/jpcnd-db-version.txt

# Changelog-Datei (optional)
changelog.url=https://www.pcnd.eu/jpcnd/version/jpcnd-changelog.txt

# Download-Seite (Browser-Öffnung)
download.url=https://www.pcnd.eu/jpcnd/download/
db.download.url=https://www.pcnd.eu/jpcnd/00download/jpcnd-adb-aktuell.db3




# Timeout in Sekunden
http.timeout=15

update.auth.enabled=true
update.auth.username=meinuser
update.auth.password=meinpass

accdb.path=data/external.accdb
